### ISSUE TITLE
Set-Up

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/pingmvp#14]
Layne:
- [x] Server
- [x] Domain
- [x] Testflight Account

Michael:
- [x] Icons for App
- [x] Facebook Page

**Comment by laynelafrance** [comment]
@mdaworthington have we sorted out the .png files needed?

**Comment by laynelafrance** [comment]
@mdaworthington can you upload the final version of the logo we end up using to #11 please, for @razvan-paul 's reference. 

@razvan-paul are you missing anything from this list or do you need anything else from us?

**Comment by PaulRBerg** [comment]
@laynekeanna Absolutely anything, with the exception of that final version logo + the logo without background for the toolbar up.
Just for reference, the Facebook Developer app was made on my account, but we can switch afterwards and grant you admin access. This won't be a problem on the long run.

**Comment by laynelafrance** [comment]
@mdaworthington do we have these to @razvan-paul now?

@razvan-paul have we fixed this now that you are uploading builds or no?
