### ISSUE TITLE
Data from Facebook

### ISSUE THREAD

**Issue by PaulRBerg** [laynelafrance/pingmvp#15]
#13 
What profile information should I retrieve from Facebook?

ID, Name, gender & profile picture are enough?

**Comment by laynelafrance** [comment]
Correct

ID, Name, Gender, Profile Picture

**Comment by laynelafrance** [comment]
Were we able to set up the account properly?

cc @mdaworthington @razvan-paul

**Comment by PaulRBerg** [comment]
@laynekeanna  Yes, I will grant you admin access when you will send me friend requests on Facebook. I can't otherwise.
