### ISSUE TITLE
Photo Upload Bug

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/pingmvp#18]
The Facebook profile photo uploaded is okay, but if you change the photo to one from your phone's library the image is distorted.

**Comment by PaulRBerg** [comment]
I don't quite get it, what do you mean by distorted? I've tested on my phone and it worked.

**Comment by PaulRBerg** [comment]
Nevermind, I sorted it out. I will put a square crop when you choose your image.

**Comment by laynelafrance** [comment]
Resolved
