### ISSUE TITLE
Formatting Problems

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/pingmvp#20]
The formatting of the buttons is a little off and the picture on the settings page still seems stretched. 

![img_2026](https://cloud.githubusercontent.com/assets/19331896/20642942/46e7dd7c-b3d1-11e6-905f-e9745671d110.PNG)
![img_2025](https://cloud.githubusercontent.com/assets/19331896/20642944/4c89bc5a-b3d1-11e6-8718-ab15a0a65624.PNG)

cc @mdaworthington

**Comment by PaulRBerg** [comment]
I know what exactly what is has. A different screen sizes issue. It will be done asap.

**Comment by PaulRBerg** [comment]
Solved in Build no. 5 on TestFlight
