### ISSUE TITLE
OneSignal account

### ISSUE THREAD

**Issue by PaulRBerg** [laynelafrance/pingmvp#22]
For the push notifications, I'm going to use OneSignal. I have been using their software for a long period of time and they are simply great. There are many benefits in favour of using a 3rd party provider:
- The Apple SDK updates are maintained by them - You don't have to pay me again after 2 months when software is updated
- It's completely FREE! Of course, until you reach a certain number of users and a certain number of notifications. But that number is very large and when you are big it's a no-brainer to invest in your app
- It will be far more faster for me to develop. With OneSignal it will take 1 day, whereas if you would like to make the push notifications from scratch it will take ±4 days + it will cost more for my time + there may be a couple of server issues because Apple obliges you to not have a shared hosting (Which afaik on siteground.com this is what you have now, that's why it's cheap): https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/APNSOverview.html#//apple_ref/doc/uid/TP40008194-CH8-SW1

If you are ok with this, please make an account on onesignal.com and grant me access by telling me the email and password. Thanks!

**Comment by laynelafrance** [comment]
Sounds good to me, thanks for the very thorough explanation, you're right that sounds like a much better choice.

Account created. I'll PM you details.
