### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/pingmvp#7]
The `status page` is where the user will be directed after the `selection screen`. It will indicate the status of other users in the area and will show a user whether or not the other user 
1) Matched (green) 
2) YOU haven't responded (orange) 
3) THEY haven't responded (grey)

![5pingmatches2 5](https://cloud.githubusercontent.com/assets/23647846/20651151/32db1326-b494-11e6-95cb-5082e5d3b212.jpg)

**Comment by laynelafrance** [comment]
$100

**Comment by laynelafrance** [comment]
Matching only - No messaging

**Comment by laynelafrance** [comment]
<img width="298" alt="screen shot 2016-11-27 at 11 20 38" src="https://cloud.githubusercontent.com/assets/19331896/20651163/7955b19e-b494-11e6-8619-576193391d19.png">

@razvan-paul above is the action a user will take and what should result on the `status page`

cc @mdaworthington

**Comment by mdaworthington** [comment]
Must remember to test bug that was found with loading feature when status page is done:
Upon opening the app, loading feature worked with users image in the middle. 
After swiping right/left on a user and the loading icon coming back on screen, photo icon was no longer shown. 

I'll test to make sure that has been fixed.
@razvan-paul

**Comment by PaulRBerg** [comment]
Page done in the build no. 6 which was just uploaded. Small observation: in the table you provided me above, it's not really clear what to do when 'Your Action' is 'Clicked Heart' and 'Their Action' is 'Clicked X' so I supposed to follow the love sharing principle of Ping and to hide the status item if one of the users dispinged the other one. Is that all right?

**Comment by laynelafrance** [comment]
Sorry, you're right, I left out a case, but good assumption - yes don't show [ `don't render` ] if you `click heart` and they `click x`

cc @razvan-paul @mdaworthington

**Comment by laynelafrance** [comment]
Will close this once @mdaworthington transfers funds

cc @razvan-paul
