### ISSUE TITLE
Loading Page & Finding Users in Range

### ISSUE THREAD

**Issue by laynelafrance** [laynelafrance/pingmvp#9]
This should use an iPhone's compass to find fellow users within a 50 meter radius of the user. This information will populate the `selection screen`. When the application is processing this information or when it is waiting for more users to come into range it should display the `loading screen`.
Reference Issue #10 

![15152337_10209658476273168_431473995_o](https://cloud.githubusercontent.com/assets/19331896/20509224/0eca9f50-b01c-11e6-842a-ff09d6106324.jpg)

**Comment by laynelafrance** [comment]
Loading Page: $100
Finding Users: $150

**Comment by laynelafrance** [comment]
Will close once more testing has been done, but @mdaworthington has transferred funds.

@razvan-paul can you confirm you took issue #3 into account?

**Comment by PaulRBerg** [comment]
@laynekeanna  I have taken #3 into account. Only one issue to be solved, the image in the centre of the loading screen which disappears sometimes. But this is already done on the project I'm working on right now, so we can safely close this.
